### ISSUE TITLE
[BUG][v4.2.0] Lien en erreur 

### ISSUE THREAD

**Issue by Hoax017** [Gizmo091/synology_1fichier_hosting#18]
Lien en erreur alors que le fichier est valide et mon compte premium est bien paramétré

https://1fichier.com/?ux9c0872ivxdek6n0lwg

![image](https://github.com/Gizmo091/synology_1fichier_hosting/assets/8215575/66839031-fd30-4b4e-9a0b-c1da83ac236b)

**Comment by Gizmo091** [comment]
Bonjour, 

Le retour de l'api pour ce fichier est : 

```json
{
"status":"KO",
"message":"Owner locked #620"
}
````

J'ai remarqué quelque chose avec l'API de 1fichier, elle est moins tollérente que leur site web. On est dans la situation ou le compte utilisateur de la personne qui à uploadé le fichier sur 1fichier est locké (donc blocké par 1fichier)  mais le fichier reste accessible encore sur le siteweb.

**Comment by Gizmo091** [comment]
Il faudrait que je vois pour retourner un message d'erreur plus clair dans l'interface dans ce type de cas.

**Comment by Hoax017** [comment]
Au final, je les ai téléchargés à la main du coup, mais je peux regarder ce WE pour faire une PR pour fix ça. ou trouver un tricks.
Merci de la réponse

**Comment by Gizmo091** [comment]
Avec plaisir :) 

J'hésitais à faire une nouvelle version ou je fallback sur le crawling du site à l'ancienne .

**Comment by Hoax017** [comment]
Le "souci" c'est que le crawling est pas compatible avec la clé d'api de la config

**Comment by Gizmo091** [comment]
Yep. Mais je pensais plus à faire une api de mon côté sur un server self hosted et j'aurais crawlé serveur side.

**Comment by Gizmo091** [comment]
Fixed with #22
